name: Selenium TestNG CI
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: temurin
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and test
      run: mvn clean test
    - name: Upload ExtentReports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: extent-reports
        path: reports/ExtentReport.html
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: logs/test.log
    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/