deploy:
  runs-on: ubuntu-latest
  needs: [build]
  steps:
    - uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: extent-reports
        path: reports/
    - name: Publish reports
      run: |
        # Example: Copy reports to a server (replace with your server details)
        scp reports/ExtentReport.html user@your-server:/path/to/reports/
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
